name: Golang CI lint

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]

permissions:
  contents: read

jobs:
  golangci:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-go@v5.5.0
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1