name: Release

on:
  push:
    tags: [ '**' ]

permissions:
  contents: write

jobs:
  release:
    name: "Release application"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0
    - name: Install curl
      run: apt-get update && apt-get install --yes curl
    - name: Install syft
      env:
        SYFT_VERSION: "1.41.1" # renovate: datasource=github-releases depName=anchore/syft
      run: |
        OS="$(uname | tr '[:upper:]' '[:lower:]')"
        ARCH="$(dpkg --print-architecture)"
        curl \
          --fail \
          --location \
          --silent \
          --output syft_${SYFT_VERSION}_${OS}_${ARCH}.deb \
            "https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_${OS}_${ARCH}.deb"
        dpkg -i syft_${SYFT_VERSION}_${OS}_${ARCH}.deb
        rm syft_${SYFT_VERSION}_${OS}_${ARCH}.deb
    - uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: "v2.6.2" # renovate: datasource=github-tags depName=sigstore/cosign
    - uses: docker/setup-qemu-action@v3.7.0
    - uses: docker/setup-buildx-action@v3.12.0
    - uses: actions/setup-go@v6.2.0
      with:
        go-version: stable
    - uses: docker/login-action@v3.7.0
      with:
        registry: git.cryptic.systems
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }}
    - env:
        COSIGN_PASSPHRASE: ${{ secrets.COSIGN_PASSPHRASE }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        GITEA_TOKEN: ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }}
        GONOSUMDB: ${{ vars.GONOSUMDB }}
        GOPROXY: ${{ vars.GOPROXY }}
      uses: goreleaser/goreleaser-action@v6.4.0
      with:
        version: v2.14.0 # renovate: datasource=github-releases depName=goreleaser/goreleaser
        args: release --clean

  sync-to-hub-docker-io:
    name: "Upload Images to docker.io"
    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - name: Copy images to docker.io
      run: |
        TAG=$(echo ${{ github.ref_name }} | sed 's/v//gm')

        apt-get update --yes
        apt-get install --yes skopeo
        skopeo copy \
          --all \
          --dest-password ${{ secrets.DOCKER_IO_PASSWORD }} \
          --dest-username ${{ secrets.DOCKER_IO_USERNAME }} \
          --src-password ${{ secrets.GIT_CRYPTIC_SYSTEMS_PACKAGE_REGISTRY_TOKEN }} \
          --src-username ${{ github.repository_owner }} \
            docker://git.cryptic.systems/volker.raschek/dcmerge:${TAG} \
            docker://docker.io/volkerraschek/dcmerge:${TAG}
